### ISSUE TITLE
Bootstrap 5 Support

### ISSUE THREAD

**Issue by FrancescoBorzi** [scttcper/ngx-toastr#887]
My [app](https://github.com/azerothcore/Keira3) is running with `ngx-toastr` version `14.0.0` and Bootstrap 4.

I use `toastr-bs4-alert.scss` and it works nicely.

If I try to update it to Bootstrap 5, I get:

```
./src/assets/scss/main.scss - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: SassError: $color: theme-color-level("success", 6) is not a color.
    ╷
151 │     rgba($fill-color, 0.999999) + "' d='" + $path + "'/%3E%3C/svg%3E";
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules/ngx-toastr/toastr-bs4-alert.scss 151:5  svg-factory()
  node_modules/ngx-toastr/toastr-bs4-alert.scss 159:5  @import
  src/assets/scss/main.scss 13:9                       root stylesheet
```

More info about my system:

```
Angular CLI: 12.0.1
Node: 14.15.0
Package Manager: npm 6.14.13
OS: darwin x64

Angular: 12.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.1
@angular-devkit/build-angular   12.0.1
@angular-devkit/core            12.0.1
@angular-devkit/schematics      12.0.1
@schematics/angular             12.0.1
rxjs                            6.6.7
typescript                      4.2.4
```

**Comment by scttcper** [comment]
yeah thats a good idea. they have a toast component now too...

**Comment by NiteshSukalikar** [comment]
@FrancescoBorzi  got any solution for rgba($fill-color, 0.999999) + "' d='" + $path + "'/%3E%3C/svg%3E";  ?
if you got any alternative kindly please share !

**Comment by mrsegen** [comment]
The answer may be to replace `theme-color-level()` with `color-level()`. I see that listed as a Bootstrap 5 breaking change under Sass: https://getbootstrap.com/docs/5.0/migration/#sass

**Comment by FaabLondon** [comment]
Hello,

I was wondering if you had an update on the bug above? 

Thanks a lot for your help

Fabienne

**Comment by FrancescoBorzi** [comment]
hi @FaabLondon , I haven't tried it recently so no updates from my side

**Comment by Eonasdan** [comment]
Hello. I made this work with BS5. I created [a gist](https://gist.github.com/Eonasdan/db173d060cb98abf3eb031c078a1329c) of my setup. I should write a small blog post with more details but I hope this helps people.

**Comment by wwarby** [comment]
This is still broken. Would be great if support for Bootstrap 5 could be prioritised - it's been out for quite a few months now and it looks like the fix is relatively straightforward.

**Comment by wwarby** [comment]
@Eonasdan thanks - I had actually looked at your gist (not the blog post) - I can see I'd be able to get it working using your approach but I really don't want to add bloat to my project to work around an incompatibility issue - I don't actually have any pressing need to upgrade from Bootstrap 4 to 5 right now, it's just concerning when I'm locked into an old version of a major library like Bootstrap. If it doesn't get fixed in the next few months I'll probably make use of your approach.

**Comment by gabrie-allaigre** [comment]
@mrsegen Thanks

You have to add a multiplication to the level `shift-color($success, 6 * $theme-color-interval)`

I create a gist file for [toastr-bs5-alert.scss](https://gist.github.com/gabrie-allaigre/98a76b52c19a40e9cb94526c5185977c)

**Comment by CodersExpo** [comment]
Thanks for doing that @gabrie-allaigre but I agree with @wwarby not so much on "bloat" but more of a Band-Aid approach here. Does anyone here have any idea when this will get resolved? We don't have the option to use Bootstrap < 5. I have "ngx-toastr": "^14.2.1" and "@angular/animations": "^13.2.3" in an angular 13.2.3 project and getting:

Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: $color: theme-color-level("success", 6) is not a color.
    ╷
151 │     rgba($fill-color, 0.999999) + "' d='" + $path + "'/%3E%3C/svg%3E";
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules\ngx-toastr\toastr-bs4-alert.scss 151:5  svg-factory()
  node_modules\ngx-toastr\toastr-bs4-alert.scss 159:5  @import
  src\styles.scss 26:9                                 root stylesheet

./src/styles.scss - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: $color: theme-color-level("success", 6) is not a color.
    ╷
151 │     rgba($fill-color, 0.999999) + "' d='" + $path + "'/%3E%3C/svg%3E";
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules\ngx-toastr\toastr-bs4-alert.scss 151:5  svg-factory()
  node_modules\ngx-toastr\toastr-bs4-alert.scss 159:5  @import
  src\styles.scss 26:9

**Comment by golayp** [comment]
> @mrsegen Thanks
> 
> You have to add a multiplication to the level `shift-color($success, 6 * $theme-color-interval)`
> 
> I create a gist file for [toastr-bs5-alert.scss](https://gist.github.com/gabrie-allaigre/98a76b52c19a40e9cb94526c5185977c)

I found a small issue on your code, you should add !import to all color of text in toastr since they are not apply correctly and reder as white text

**Comment by golayp** [comment]
I've update my gist : https://gist.github.com/golayp/cd6f5c7ab8b23096f8a9cc422d34d9cf to ensure links are colored correctly according to the type of toast

**Comment by golayp** [comment]
Hi @scttcper my feeling about new bootstrap toast component is that it is too UX heavy (lots of borders), maybe to ensure a maximum features compatibility, but in most case a simple box with the correct color is sufficient. It's why I used ngx-toastr for a while with complet user adherence.

**Comment by dovvan** [comment]
Hi. I have an issue with the full width toastr and bs-5. BS have set toast-container width to max-content. 
Can't solve this. Any suggestions?

**Comment by XhmikosR** [comment]
Hey, @scttcper. Could you please let me know what's left here so that we have a toastr-bs5-alert.scss officially included in the package?

I'm personally interested in this, so I could have a look as long as someone sums up the issues.

**Comment by Nabeeh-AlSawaf** [comment]
any new updates on this ? i'm interested as well since this package is always in my projects

**Comment by grozandrei** [comment]
I am also interested in fixing this issue, any news about this?

**Comment by yildiraymeric** [comment]
We have the same problem, hoping a fix coming soon..

**Comment by XhmikosR** [comment]
@scttcper do you need something from us to land this? Bootstrap 4 is close to EOL.

**Comment by siovene** [comment]
Adding my voice to the chorus.

**Comment by XhmikosR** [comment]
@scttcper would it be possible to backport the bootstrap5 support in v14.x and v15.x too?

**Comment by siovene** [comment]
@scttcper thanks! Something must've gone wrong with the NPM release tho.

I installed 16.0.0 and `toastr-bs5-alert.scss` doesn't exist.

To be sure, I removed my node_modules, did `npm install`, checked that `node_modules/ngx-toastr/package.json` mentions version `16.0.0`, and `toastr-bs5-alert.scss` doesn't exist.

Could you have missed something?

```
$ grep toastr package.json
    "ngx-toastr": "16.0.0",
$ grep version node_modules/ngx-toastr/package.json 
  "version": "16.0.0",
$ find node_modules/ngx-toastr -name '*.scss'
node_modules/ngx-toastr/toastr-bs4-alert.scss
```

Thank you!

**Comment by siovene** [comment]
Thanks, I see now that it's fixed in 16.0.1.

**Comment by mikeandtherest** [comment]
@siovene  @scttcper The issue is indeed fixed in 16.0.1, but on the other hand ngx-toastr 16.0.1 throws errors when used with angular versions prior to v15. Does it work for you on angular v13 or v14 projects?

---

Steps to reproduce:

1. create a new angular 14 project (I'm on angular 14.2.10)
2. add ngx-toastr to it (`npm i ngx-toastr` which installs ngx-toastr 16.0.1)
3. add ToastrModule to AppModule:
        ToastrModule.forRoot({
           preventDuplicates: true
       }),
4. use ToastrService inside AppComponent
5. when running `npm start` we'll get the errors below:

![image](https://user-images.githubusercontent.com/16487780/206881900-153046d8-538b-412c-b7b4-6e55f174c89a.png)

**Comment by scttcper** [comment]
latest version only works with 15 see the table https://github.com/scttcper/ngx-toastr#dependencies @mikeandtherest

**Comment by mikeandtherest** [comment]
@scttcper That's what I figured before the table was updated. But still, ngx-toastr 15.2.2 doesn't have this issue fixed, i.e. toastr-bs4-alert.scss is still with errors and I can't import toastr-bs5-alert.scss, since it's not found.

So unless I'm migrating to angular 15 (which is not possible unfortunately on our project), I'm out of ideas on how I can use the fix from ngx-toastr 16.0.1 on an angular 14 project.

**Comment by scttcper** [comment]
Just copy paste the css

**Comment by Hetvip17** [comment]
> 🎉 This issue has been resolved in version 16.0.0 🎉
> 
> The release is available on:
> 
> * [npm package (@latest dist-tag)](https://www.npmjs.com/package/ngx-toastr/v/16.0.0)
> * [GitHub release](https://github.com/scttcper/ngx-toastr/releases/tag/v16.0.0)
> 
> Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot 📦🚀

hey @scttcper, I am still facing the same issue even after updating to version 16.0.0 . I am using angular 15
